package fr.msa.imas_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dossier implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Dossier() {
    }




}